USE [KPI_App]
GO

/****** Object:  StoredProcedure [dbo].[EXTGEN_CLM_GenerateOrderPickListSp]    Script Date: 08/30/2017 15:48:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/* $Header: /ApplicationDB/Stored Procedures/CLM_GenerateOrderPickListSp.sp 14    9/23/14 1:39a Ychen1 $ */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2010 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
*************************************************************** 
*/
/* $Archive: /ApplicationDB/Stored Procedures/CLM_GenerateOrderPickListSp.sp $
 *
 * SL9.00 14 184567 Ychen1 Tue Sep 23 01:39:08 2014
 * Able to generate orders for Orders with external warehoues
 * 184567: Filter out those co with exteranl controlled wms.
 *
 * SL8.02 13 rs4588 Dahn Thu Mar 04 10:24:22 2010
 * RS4588 Copyright header changes
 *
 * SL8.02 12 rs4588 Dahn Thu Mar 04 09:33:38 2010
 * RS4588 Copyright header changes
 *
 * SL8.01 11 rs3953 Vlitmano Tue Aug 26 16:42:27 2008
 * RS3953 - Changed a Copyright header?
 *
 * SL8.01 10 rs3953 Vlitmano Mon Aug 18 15:07:20 2008
 * Changed a Copyright header information(RS3959)
 *
 * SL8.00 9 106508 Hcl-jainami Mon Oct 22 10:41:01 2007
 * Generate Order Pick List is not printing the Pick List
 * Issue # 106459
 * Reset the value of variable "@PEndDueDate" with dbo.DayEndOf(@PEndDueDate).
 *
 * SL8.00 8 RS2968 nkaleel Sun Feb 25 23:42:19 2007
 * changing copyright information(RS2968)
 *
 * SL8.00 6 95887 pcoate Wed Aug 30 07:37:09 2006
 * Generate Order Pick List form does not display the message about credit hold.
 * Issue 95887 - Include a message in the result set for orders on credit hold.
 *
 * SL8.00 5 RS2968 prahaladarao.hs Thu Jul 13 02:42:10 2006
 * RS 2968, Name change CopyRight Update.
 *
 * SL8.00 4 RS2968 prahaladarao.hs Tue Jul 11 05:22:12 2006
 * RS 2968
 * Name change CopyRight Update.
 *
 * SL7.05 3 91818 NThurn Fri Jan 06 14:23:08 2006
 * Inserted standard External Touch Point call.  (RS3177)
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE [dbo].[EXTGEN_CLM_GenerateOrderPickListSp] (
  @PStartCoNum   CoNumType
, @PEndCoNum     CoNumType
, @PStartDueDate DateType
, @PEndDueDate   DateType
, @PStartWhse    WhseType
, @PEndWhse      WhseType
, @PStartCustNum CustNumType
, @PEndCustNum   CustNumType
, @PStartCustSeq CustSeqType
, @PEndCustSeq   CustSeqType
, @PParmsSite     SiteType
)
AS

   ---- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   --IF OBJECT_ID(N'dbo.EXTGEN_CLM_GenerateOrderPickListSp') IS NOT NULL
   --BEGIN
   --   DECLARE @EXTGEN_SpName sysname
   --   SET @EXTGEN_SpName = N'dbo.EXTGEN_CLM_GenerateOrderPickListSp'
   --   -- Invoke the ETP routine, passing in (and out) this routine's parameters:
   --   EXEC @EXTGEN_SpName
   --      @PStartCoNum
   --      , @PEndCoNum
   --      , @PStartDueDate
   --      , @PEndDueDate
   --      , @PStartWhse
   --      , @PEndWhse
   --      , @PStartCustNum
   --      , @PEndCustNum
   --      , @PStartCustSeq
   --      , @PEndCustSeq
   --      , @PParmsSite
 
   --   -- ETP routine must take over all desired functionality of this standard routine:
   --   RETURN 0
   --END
   ---- End of Generic External Touch Point code.
 
DECLARE
  @Severity INT
, @Infobar  InfobarType

SET @Severity = 0


-- Return Orders which need a Pick List Printed
SET @PStartCoNum    = ISNULL(dbo.ExpandKyByType('CoNumType', @PStartCoNum), dbo.LowString('CoNumType'))
SET @PEndCoNum      = ISNULL(dbo.ExpandKyByType('CoNumType', @PEndCoNum), dbo.HighString('CoNumType'))
SET @PStartDueDate  = ISNULL(@PStartDueDate, dbo.LowDate())
SET @PEndDueDate    = ISNULL(dbo.DayEndOf(@PEndDueDate), dbo.HighDate())
SET @PStartWhse     = ISNULL(@PStartWhse, dbo.LowString('WhseType'))
SET @PEndWhse       = ISNULL(@PEndWhse, dbo.HighString('WhseType'))
SET @PStartCustNum  = ISNULL(dbo.ExpandKyByType('CustNumType', @PStartCustNum), dbo.LowString('CustNumType'))
SET @PEndCustNum    = ISNULL(dbo.ExpandKyByType('CustNumType', @PEndCustNum), dbo.HighString('CustNumType'))
SET @PStartCustSeq  = ISNULL(@PStartCustSeq, dbo.LowInt())
SET @PEndCustSeq    = ISNULL(@pEndCustSeq, dbo.HighInt())

-- Build error message in case it's needed during select.
EXEC dbo.MsgAppSp @Infobar OUTPUT, 'I=IsCompare='
   , '@co.credit_hold'
   , '@:logical:yes'

-- The invoices to be posted are returned to the client.
-- The Order of the Select was taken from the progress for each loops in
-- co/co14-r.p

-- May need to add logic later for linking to Shipping Processing Orders

SELECT DISTINCT
  co.co_num
, coitem.whse
, co.cust_num
, co.cust_seq
, CASE WHEN credit_hold = 1 THEN @Infobar ELSE NULL END
FROM co
INNER JOIN coitem ON (coitem.co_num = co.co_num)
INNER JOIN whse ON (coitem.whse = whse.whse)
WHERE co.stat = 'O'
AND   (co.type = 'R' OR co.type = 'B') 

AND   (co.co_num   BETWEEN @PStartCoNum AND @PEndCoNum)
AND   (co.cust_num BETWEEN @PStartCustNum AND @PEndCustNum)
AND   (co.cust_seq BETWEEN @PStartCustSeq AND @PEndCustSeq)
AND   coitem.stat = 'O'
AND   (coitem.whse     BETWEEN @PStartWhse AND @PEndWhse)
AND   (coitem.due_date BETWEEN @PStartDueDate AND @PEndDueDate)
AND   coitem.ship_site = @PParmsSite
AND   whse.controlled_by_external_wms = 0
ORDER BY co.cust_num, co.cust_seq, co.co_num, coitem.whse

RETURN @Severity

GO


