USE [KPI_App]
GO

/****** Object:  StoredProcedure [dbo].[EXTGEN_Rpt_GenerateOrderPickListSp]    Script Date: 08/30/2017 15:48:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/* $Header: /ApplicationDB/Stored Procedures/Rpt_GenerateOrderPickListSp.sp 56    3/19/15 3:34a Dyang2 $ */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2010 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
*************************************************************** 
*/
/* $Archive: /ApplicationDB/Stored Procedures/Rpt_GenerateOrderPickListSp.sp $
 *
 * SL9.00 56 191307 Dyang2 Thu Mar 19 03:34:11 2015
 * After preview Quick Pick List, and then modify CO Line Qty - "Unable to perform update..." is displayed
 * Issue 191307: Skip update RecordDate column when generate order pick list to avoid update problem after coitem generate pick list.
 *
 * SL9.00 55 184567 Ychen1 Tue Sep 23 01:41:21 2014
 * Able to generate orders for Orders with external warehoues
 * 184567: Add wms check to decide whether to generate order pick list.
 *
 * SL9.00 54 181840 Sxu Fri Jul 25 04:26:38 2014
 * Locations not printing correctly on Pick List
 * Issue 181840 - modify alias for itemloc
 *
 * SL9.00 53 181840 Sxu Fri Jul 25 04:09:23 2014
 * Locations not printing correctly on Pick List
 * Issue 181840 - Modify SP Rpt_GenerateOrderPickListSp to list location in both detail and summary part by location Alphabetical Order when 'List by Stock Location’ is checked, else list location by rank.
 *
 * SL9.00 52 181840 Sxu Thu Jul 24 22:50:54 2014
 * Locations not printing correctly on Pick List
 * Issue 181840 - Modify SP Rpt_GenerateOrderPickListSp to list location in both detail and summary part by location Alphabetical Order when 'List by Stock Location’ is checked, else list location by rank.
 *
 * SL9.00 51 179576 Lpeng Thu Jul 17 05:20:46 2014
 * RS5618 coding and schema
 * RS5618(Issue 179576)
 * Need not prevent
 *
 * SL9.00 50 179576 Lzhan Fri Jul 11 05:36:54 2014
 * Issue 179576: added logic of preventing for External warehouse.
 *
 * SL9.00 49 177454 pgross Thu Apr 17 17:25:54 2014
 * GenerateOrderPickList fails in BGTaskHistory with no valid error message
 * removed transaction block handling and Journal buffering
 *
 * SL9.00 48 173790 calagappan Wed Jan 08 11:27:08 2014
 * Messages are in default language instead of users’ language after Generate Order Pick List utility is performed
 * Call CloseSessionContextSp to delete DefineVariables only when not using existing session ID
 *
 * SL9.00 47 171385 Mding2 Mon Dec 23 01:18:47 2013
 * Germany Country Pack - Report layout changes
 * Issue 171385 - Re-write logic for using Alternate Address Report Formatting.
 *
 * SL8.04 46 161264 Ehe Tue Apr 23 23:19:51 2013
 * Generate Order Pick List Report not sorting be Location
 * Issue 161264
 * Change the report output to order by the  location alphabetically.
 *
 * SL8.04 45 RS4615 jzhou Thu Mar 07 21:30:49 2013
 * RS4615:
 * Replace InitSessionSp with InitSessionContextWithUserSp.
 * Remove ClearSessionSp.
 *
 * SL8.04 44 RS4615 Ezi Wed Jan 09 02:16:28 2013
 * RS4615 - Multi - Add Site within a Site Functionality
 *
 * SL8.04 43 RS4615 Jsun Wed Dec 26 03:16:38 2012
 * RS4615: Multi - Add Site within a Site Functionality
 *
 * SL8.03 42 139412 Sxu Thu Jul 28 05:42:54 2011
 * Two issues on the report generated by the Generate Order Pick List form.
 * Issue139412 - With Form Print Line/Release Description selected, report will show description for the item, so issue1 is not a real issue
 *
 * SL8.03 41 139412 Sxu Wed Jul 27 03:42:14 2011
 * Two issues on the report generated by the Generate Order Pick List form.
 * Issue139412 - update the result set of UM and Description
 *
 * SL8.03 40 RS4581 Tding Thu May 05 06:21:19 2011
 * RS4581 add manufacturer id and item
 *
 * SL8.02 39 rs4588 Dahn Thu Mar 04 16:28:56 2010
 * rs4588 copyright header changes.
 *
 * SL8.02 38 121361 Mewing Mon Oct 12 14:51:33 2009
 * SL8.02 00 121361  All references to BatchId2Type need to be changed back to BatchIdType.  This checkin will affect stored procedures, triggers, functions.
 * Schema, property classes and component classes will be done seperately.
 *
 * SL8.01 37 118985 Cajones Mon May 18 14:46:59 2009
 * Unable to generate a Batch ID more than 99 at Shipping Processing Orders
 * Issue:118985,APAR:115322 - Changed references of type BatchIdType (defined as tinyint) to new UDDT BatchId2Type (defined as int).  This change is to allow the user to enter a 6 digit batch id number.
 *
 * SL8.01 36 118350 bpettit Tue Mar 24 15:34:46 2009
 * There needs to be an option for Increment Date on the date range field.
 * 116678 - Add offset date fields
 *
 * SL8.01 35 116816 Clarsco Tue Feb 17 12:00:23 2009
 * Generate Order Pick List report, when executed multiple times in quick succession the report fails with error:
 * Fixed 116816
 * Eliminate usage of tt_order_pick_list, INSERT directly into #tt_orderpicklist_results moved to GenerateOrderPickListSp.
 * Added READUNCOMMITTED to the following FROM clauses:
 * Invparms, co, coitem and itemloc.
 *
 * SL8.01 34 117619 pgross Thu Feb 12 14:06:39 2009
 * Generate Order Pick List initiates a session and may not always clean this session up
 * attempt to attach to an existing license instead of creating a new one
 *
 * SL8.01 33 rs3953 Vlitmano Tue Aug 26 18:59:48 2008
 * RS3953 - Changed a Copyright header?
 *
 * SL8.01 32 rs3953 Vlitmano Mon Aug 18 15:37:59 2008
 * Changed a Copyright header information(RS3959)
 *
 * SL8.01 31 108189 Snenavat Wed Apr 09 18:32:57 2008
 * Unable to modify GeneratePickListReport132 in Crystal Report
 * Issue -108189 
 *  ?IF @@ROWCOUNT > 0? is added
 *
 * SL8.00 30 106542 Clarsco Mon Nov 05 17:30:49 2007
 * The GenerateOrderPickList creates a new Syteline session for the user each time the GenerateOrderPickList is executed, thus the user will end up with multiple sessions being used, thus using multiple licenses for the one user.  
 * Fixed bug 106542
 * Added a call to ClearSessionSp
 *
 * SL8.00 29 101463 pgross Thu Aug 02 15:30:19 2007
 * User initials are blank on the material transaction report for a CO shipment when the transaction is created from the generate order pick list.
 * initialize user context
 *
 * SL8.00 28 101669 pgross Fri Jun 08 09:31:46 2007
 * Transactions are occasionally being stranded in the tmp_mass_journal table and not making it into the journal
 * 1)  ensure that the program performs a clean exit when an error is detected
 * 2)  added a transaction block
 *
 * SL8.00 27 100359 Hcl-tayamoh Fri Apr 20 02:09:01 2007
 * Generate Order Pick List Report - Quantity display needs expanded to 3 decimal places to the right of the decimal.
 * Issue 100359
 * unit qty format and tota qty format and decimal places
 * Added fields in report result table  and value are fetched  from inventory parameter table.
 *
 * SL8.00 26 RS2968 nkaleel Fri Feb 23 04:51:10 2007
 * changing copyright information(RS2968)
 *
 * SL8.00 25 RS2968 prahaladarao.hs Wed Jul 12 01:46:20 2006
 * RS 2968, Name change CopyRight Update.
 *
 * SL8.00 24 94457 Hcl-sharpar Fri May 26 09:10:12 2006
 * Customer Item Number is not printing on the Order Pick List
 * Issue 94457
 * Corrected the order of sorting of the locations as per their rank.
 *
 * SL8.00 23 93251 NThurn Thu Mar 16 08:27:16 2006
 * Repaired ETP call.  (93251)
 *
 * SL8.00 22 90161 magler Thu Mar 09 22:47:43 2006
 * Message handling in reports
 * Handle the case of no active transaction
 *
 * SL8.00 21 90161 jabraham Thu Mar 09 15:57:51 2006
 * Message handling in reports
 * ISSUE 90161
 * Added code for handling when error occurs.
 *
 * SL8.00 20 92248 Hcl-mehtviv Wed Feb 01 01:07:16 2006
 * Generate Order Pick List not printing in any order when printing Customer Order Blanket Releases.
 * Issue  92248:
 * Added parameters:
 * 1)  coitem_co_release,  and
 * 2)  summ_itemdet_co_release.
 * in the "order by"  of  final  "select"  statement of the table
 * #tt_orderpicklist_results.
 *
 * SL7.05 19 89543 hcl-singind Fri Dec 16 07:09:08 2005
 * Report format splitting line detail between pages
 * Issue # 89543
 * 1. Unused variables has been removed.
 * 2. Unnecessary comments have been removed.
 * 3. Indentations has been done for whole sp.
 * 4. All the sps and functions has been prefixed with ".dbo".
 *
 * SL7.05 18 89336 Grosphi Thu Sep 29 12:51:25 2005
 * when selecting on a RowPointer column, do not convert it to NVARCHAR
 *
 * SL7.05 17 80051 Hcl-singsun Wed Aug 10 10:11:34 2005
 * Issue #80051
 *
 * SL7.04 16 85343 Grosphi Tue Feb 01 16:25:02 2005
 * allow for 55 characters in displayed feature string
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE [dbo].[EXTGEN_Rpt_GenerateOrderPickListSp] 
(  @PSessionIdChar                        NVARCHAR(255)  = NULL    --Datatype @PSessionId is changed from RowPointerType to NVARCHAR (255)due to a limitation of Crystal Reports 9.0. Crystal Reports 9.0 does not identify the datatype RowPointerType
 , @PStartCoNum                           CoNumType      = NULL
 , @PEndCoNum                             CoNumType      = NULL
 , @PStartDueDate                         DateType       = NULL
 , @PEndDueDate                           DateType       = NULL
 , @PStartWhse                            WhseType       = NULL
 , @PEndWhse                              WhseType       = NULL
 , @PStartCustNum                         CustNumType    = NULL
 , @PEndCustNum                           CustNumType    = NULL
 , @PStartCustSeq                         CustSeqType    = NULL
 , @PEndCustSeq                           CustSeqType    = NULL
 , @PParmsSite                            SiteType       = NULL
 , @PPostDate                             DateType       = NULL    -- Post As of Date
 , @PPostMatlIssues                       ListYesNoType  = NULL    -- Post Material Issues
 , @PBarLoc                               ListYesNoType  = NULL    -- Barcode Location
 , @PShowExternal                         FlagNyType     = NULL    -- Part of replacement for original "Print Line/Release Text"
 , @PShowInternal                         FlagNyType     = NULL    -- Part of replacement for original "Print Line/Release Text"
 , @PDisplayHeader                        ListYesNoType  = NULL
 , @PPrintBc                              ListYesNoType  = NULL    -- Print Barcode Format
 , @PPrint80                              ListYesNoType  = NULL    -- Print 80 Column Pick List
 , @PDetSummBoth                          NCHAR(1)       = NULL    -- Detail Summary Or Both
 , @PPrItemCi                             NCHAR(2)       = NULL    -- Print Item Or Customer Item
 , @PPrSerialNumbers                      ListYesNoType  = NULL    -- Include Serial Numbers
 , @PPrPlanItemMatl                       ListYesNoType  = NULL    -- Print Planning Item Materials
 , @PPrStdOrderText                       ListYesNoType  = NULL    -- Print Standard Order Text
 , @PDisplayDescription                   FlagNyType     = NULL    -- For printing "first line" of notes.
 , @PListByLoc                            ListYesNoType  = NULL    -- List By Stock Location
 , @PPickwarn                             NCHAR(1)       = NULL    -- Reprint Pick List Items
 , @PSuppressErrorWhenCustomerLcrNotReqd  ListYesNoType  = NULL
 , @PSkipOrderLineCycCnt                  ListYesNoType  = NULL
 , @PProcessBatchId                       BatchIdType    = NULL    -- Use if we are planning on doing processing by batch ID
 , @TaskId                                TaskNumType    = NULL
 , @pPrintManufacturerItem                ListYesNoType  = NULL
 , @DueDateStartingOffset                 DateOffsetType = NULL
 , @DueDateEndingOffset                   DateOffsetType = NULL
 , @PostDateOffset                        DateOffsetType = NULL

 , @pSite SiteType = NULL
) AS

SET XACT_ABORT ON
-- A session context is created so session variables can be used.
DECLARE
  @RptSessionID RowPointerType
, @PSessionID   RowPointerType
, @LowCharacter  HighLowCharType
, @HighCharacter HighLowCharType
, @Username sysname
, @IfUsingExistingSession ListYesNoType

select @Username = RequestingUser
from bgtaskhistory with (readuncommitted)
where tasknumber = @TaskId

-- try to re-use an existing license
if @Username is not null
   select @RptSessionID = ConnectionID
   from ConnectionInformation with (readuncommitted)
   where UserName = @Username
set @IfUsingExistingSession = case when @RptSessionID is not null and @Username is not null then 1 else 0 end

EXEC dbo.InitSessionContextSp
  @ContextName = 'Rpt_GenerateOrderPickListSp'
, @SessionID   = @RptSessionID OUTPUT
, @Site        = @pSite

SET @LowCharacter  = dbo.LowCharacter()
SET @HighCharacter = dbo.HighCharacter()

--_KPI If this Order is Printed with the BackOrder Flag, mark the order as backordered



DECLARE
  @Severity    INT
, @CoCoNum     CoNumType
, @CoitemWhse  WhseType
, @CoCustItem  CustNumType
, @CoSeq       CustSeqType
, @Infobar     InfobarType
, @PText       FormNameType
, @TProcessBatchId BatchIdType
, @SpName      SYSNAME

IF @PProcessBatchId IS NOT NULL AND @PProcessBatchId <> 0
   SET @TProcessBatchId = @PProcessBatchId
ELSE
   SET @TProcessBatchId = NULL

SET @PSessionId = ISNULL(@PSessionIdChar, dbo.SessionIDSp())

DECLARE
  @QtyUnitFormat nvarchar(60)
, @PlacesQtyUnit tinyint
, @QtyTotlFormat nvarchar(60)
, @PlacesQtyTot tinyint

SELECT @QtyUnitFormat = qty_unit_format, 
       @PlacesQtyUnit = places_qty_unit,
       @PlacesQtyTot  = places_qty_Tot, 
       @QtyTotlFormat = qty_totl_format
FROM invparms WITH (READUNCOMMITTED)

SET @QtyUnitFormat = dbo.FixMaskForCrystal( @QtyUnitFormat, dbo.GetWinRegDecGroup() )

SET @QtyTotlFormat = dbo.FixMaskForCrystal( @QtyTotlFormat, dbo.GetWinRegDecGroup() )

DECLARE
  @TtOrderPickListItemInfo_TtItemtot_Whse          WhseType
, @TtOrderPickListItemInfo_TtItemtot_Item          ItemType
, @TtOrderPickListItemInfo_TtItemtot_UM            UMType
, @TtOrderPickListItemInfo_TtItemtot_QtyRequired   QtyUnitType
, @TtOrderPickListItemInfo_TtItemtot_QtyOnHand     QtyUnitType
, @TtOrderPickListItemInfo_TtItemloclot_Loc        LocType
, @TtOrderPickListItemInfo_TtItemloclot_Lot        LotType
, @TtOrderPickListItemInfo_CoitemManufacturerId    ManufacturerIdType
, @TtOrderPickListItemInfo_CoitemManufacturerItem  ManufacturerItemType
, @TtOrderPickListItemInfo_TcQtuRequired           QtyUnitType
, @TtOrderPickListItemInfo_TtItemloclot_QtyOnHand  QtyUnitType
, @TtOrderPickListItemInfo_CustaddrName            NameType
, @TtOrderPickListItemInfo_TtItemdet_CoNum         CoNumType
, @TtOrderPickListItemInfo_TtItemdet_CoLine        CoLineType
, @TtOrderPickListItemInfo_TtItemdet_CoRelease     CoReleaseType
, @TtOrderPickListItemInfo_TtItemdet_UM            UMType
, @TtOrderPickListItemInfo_TtItemdet_QtyRequired   QtyUnitType

DECLARE
  @TtPickList_CoContact             ContactType
, @TtPickList_CoCustNum             CustNumType
, @TtPickList_CoCustPo              CustPoType
, @TtPickList_CoCustSeq             CustSeqType
, @TtPickList_TLcr                  LongListType
, @TtPickList_CoitemRowPointer      RowPointerType
, @TtPickList_CoparmsCoText1        ReportTxtType
, @TtPickList_CoparmsCoText2        ReportTxtType
, @TtPickList_CoparmsCoText3        ReportTxtType
, @TtPickList_CoCoNum               CoNumType
, @TtPickList_WhseWhse              WhseType
, @TtPickList_CoitemCoLine          CoLineType
, @TtPickList_CoitemDueDate         DateType
, @TtPickList_CoitemQtyOrdered      QtyUnitNoNegType
, @TtPickList_CoitemTcQtuRequired1  QtyUnitNoNegType
, @TtPickList_CoitemTPickwarn2      LongListType
, @TtPickList_CoitemCustItem        CustItemType
, @TtPickList_CoitemTcQtuSQty1      QtyUnitNoNegType
, @TtPickList_CoitemTcQtuShort1     QtyUnitNoNegType
, @TtPickList_CoitemSLoc            LocType
, @TtPickList_CoitemSLot            LotType
, @TtPickList_CoitemTcQtudOnHand1   QtyUnitType
, @TtPickList_CoitemTException      LongListType
, @TtPickList_CoitemTcQtuRsvdQty1   QtyUnitNoNegType
, @TtPickList_CoitemCoRelease       CoReleaseType
, @TtPickList_CoitemItem            ItemType
, @TtPickList_CoitemItemUM          UMType
, @TtPickList_CoitemDescription     DescriptionType
, @TtPickList_CoitemManufacturerId  ManufacturerIdType
, @TtPickList_CoitemManufacturerItem ManufacturerItemType
, @TtPickList_CustBillToAddr1       AddressType
, @TtPickList_CustBillToAddr2       AddressType
, @TtPickList_CustBillToAddr3       AddressType
, @TtPickList_CustBillToAddr4       AddressType
, @TtPickList_CustBillToCity        CityType
, @TtPickList_CustBillToCountry     CountryType
, @TtPickList_CustBillToName        NameType
, @TtPickList_CustBillToState       StateType
, @TtPickList_CustBillToZip         PostalCodeType
, @TtPickList_CustBillToContact     ContactType
, @TtPickList_CustBillToPhone       PhoneType
, @TtPickList_CustCredHold          InfobarType
, @TtPickList_CustShipcodeDesc      DescriptionType
, @TtPickList_CustShipToAddr1       AddressType
, @TtPickList_CustShipToAddr2       AddressType
, @TtPickList_CustShipToAddr3       AddressType
, @TtPickList_CustShipToAddr4       AddressType
, @TtPickList_CustShipToCity        CityType
, @TtPickList_CustShipToCountry     CountryType
, @TtPickList_CustShipToName        NameType
, @TtPickList_CustShipToState       StateType
, @TtPickList_CustShipToZip         PostalCodeType
, @TtPickList_CustShipToContact     ContactType
, @TtPickList_CustShipToPhone       PhoneType
, @TtPickList_CustTermsDesc         DescriptionType
, @TtPickList_TmpSerSerNum          SerNumType
, @TtPickList_CoDConfigFeatStr      FeatTemplateType
, @TtPickList_CoDConfigQtyConv      QtyPerType
, @TtPickList_CoDConfigUM           UMType
, @TtPickList_CoDConfigDescription  DescriptionType
, @TtPickList_NoteExists            INT

-- Summary Data
, @TtPickListSumm_TtItemtotWhse           WhseType
, @TtPickListSumm_TtItemtotItem           ItemType
, @TtPickListSumm_TtItemtotUM             UMType
, @TtPickListSumm_TtItemtotQtyRequired    QtyUnitType
, @TtPickListSumm_TtItemtotQtyOnHand      QtyUnitType
, @TtPickListSumm_TtItemloclotLoc         LocType
, @TtPickListSumm_TtItemloclotLot         LotType
, @TtPickListSumm_TtItemManufacturerId    ManufacturerIdType
, @TtPickListSumm_TtItemManufacturerItem  ManufacturerItemType
, @TtPickListSumm_TcQtuRequired           QtyUnitType
, @TtPickListSumm_TtItemloclotQtyOnHand   QtyUnitType
, @TtPickListSumm_CustaddrName            NameType
, @TtPickListSumm_TtItemdetCoNum          CoNumType
, @TtPickListSumm_TtItemdetCoLine         CoLineType
, @TtPickListSumm_TtItemdetCoRelease      CoReleaseType
, @TtPickListSumm_TtItemdetUM             UMType
, @TtPickListSumm_TtItemdetQtyRequired    QtyUnitType
, @TtPickList_Summary                     FlagNyType

IF OBJECT_ID('tempdb..#tt_orderpicklist_results') IS NULL
   SELECT
       @TtPickList_CoContact                   AS co_contact
     , @TtPickList_CoCustNum                   AS co_cust_num
     , @TtPickList_CoCustPo                    AS co_cust_po
     , @TtPickList_CoCustSeq                   AS co_cust_seq
     , @TtPickList_TLcr                        AS t_lcr
     , @TtPickList_CoitemRowPointer            AS coitem_RowPointer
     , @TtPickList_CoparmsCoText1              AS coparms_co_text_1
     , @TtPickList_CoparmsCoText2              AS coparms_co_text_2
     , @TtPickList_CoparmsCoText3              AS coparms_co_text_3
     , @TtPickList_CoCoNum                     AS co_co_num
     , @TtPickList_WhseWhse                    AS whse_whse
     , @TtPickList_CoitemCoLine                AS coitem_co_line
     , @TtPickList_CoitemDueDate               AS coitem_due_date
     , @TtPickList_CoitemQtyOrdered            AS coitem_qty_ordered
     , @TtPickList_CoitemTcQtuRequired1        AS tc_qtu_required1
     , @TtPickList_CoitemTPickwarn2            AS t_pickwarn2
     , @TtPickList_CoitemCustItem              AS coitem_cust_item
     , @TtPickList_CoitemTcQtuSQty1            AS tc_qtu_s_qty1
     , @TtPickList_CoitemTcQtuShort1           AS tc_qtu_short1
     , @TtPickList_CoitemSLoc                  AS s_loc
     , @TtPickList_CoitemSLot                  AS s_lot
     , @TtPickList_CoitemTcQtudOnHand1         AS tc_qtud_on_hand1
     , @TtPickList_CoitemTException            AS t_exception
     , @TtPickList_CoitemTcQtuRsvdQty1         AS tc_qtu_rsvd_qty1
     , @TtPickList_CoitemCoRelease             AS coitem_co_release
     , @TtPickList_CoitemItem                  AS coitem_item
     , @TtPickList_CoitemItemUM                AS item_u_m
     , @TtPickList_CoitemDescription           AS description
     , @TtPickList_CoitemManufacturerId        As manufacturer_id
     , @TtPickList_CoitemManufacturerItem      As manufacturer_item
     , @TtPickList_CustBillToAddr1             AS billto_addr1
     , @TtPickList_CustBillToAddr2             AS billto_addr2
     , @TtPickList_CustBillToAddr3             AS billto_addr3
     , @TtPickList_CustBillToAddr4             AS billto_addr4
     , @TtPickList_CustBillToCity              AS billto_city
     , @TtPickList_CustBillToCountry           AS billto_country
     , @TtPickList_CustBillToName              AS billto_name
     , @TtPickList_CustBillToState             AS billto_state
     , @TtPickList_CustBillToZip               AS billto_zip
     , @TtPickList_CustBillToContact           AS billto_contact
     , @TtPickList_CustBillToPhone             AS billto_phone
     , @TtPickList_CustCredHold                AS cred_hold
     , @TtPickList_CustShipcodeDesc            AS shipcode_desc
     , @TtPickList_CustShipToAddr1             AS shipto_addr1
     , @TtPickList_CustShipToAddr2             AS shipto_addr2
     , @TtPickList_CustShipToAddr3             AS shipto_addr3
     , @TtPickList_CustShipToAddr4             AS shipto_addr4
     , @TtPickList_CustShipToCity              AS shipto_city
     , @TtPickList_CustShipToCountry           AS shipto_country
     , @TtPickList_CustShipToName              AS shipto_name
     , @TtPickList_CustShipToState             AS shipto_state
     , @TtPickList_CustShipToZip               AS shipto_zip
     , @TtPickList_CustShipToContact           AS shipto_contact
     , @TtPickList_CustShipToPhone             AS shipto_phone
     , @TtPickList_CustTermsDesc               AS terms_desc
     , @TtPickList_TmpSerSerNum                AS tmp_ser_ser_num
     , @TtPickList_CoDConfigFeatStr            AS co_d_config_feat_str
     , @TtPickList_CoDConfigQtyConv            AS co_d_config_qty_conv
     , @TtPickList_CoDConfigUM                 AS co_d_config_u_m
     , @TtPickList_CoDConfigDescription        AS co_d_config_desc
     , @TtPickList_NoteExists                  AS NoteExists

     --Summary Data
     , @TtPickListSumm_TtItemtotWhse           AS summ_itemtot_whse
     , @TtPickListSumm_TtItemtotItem           AS summ_itemtot_item
     , @TtPickListSumm_TtItemtotUM             AS summ_itemtot_um
     , @TtPickListSumm_TtItemtotQtyRequired    AS summ_itemtot_qty_req
     , @TtPickListSumm_TtItemtotQtyOnHand      AS summ_itemtot_qty_on_hand
     , @TtPickListSumm_TtItemloclotLoc         AS summ_itemloclot_loc
     , @TtPickListSumm_TtItemloclotLot         AS summ_itemloclot_lot
     , @TtPickListSumm_TtItemManufacturerId    As summ_itemmanufacturer_id
     , @TtPickListSumm_TtItemManufacturerItem  As summ_itemmanufacturer_item
     , @TtPickListSumm_TcQtuRequired           AS summ_tc_qtu_required
     , @TtPickListSumm_TtItemloclotQtyOnHand   AS summ_itemloclot_qtyonhand
     , @TtPickListSumm_CustaddrName            AS summ_custaddr_name
     , @TtPickListSumm_TtItemdetCoNum          AS summ_itemdet_co_num
     , @TtPickListSumm_TtItemdetCoLine         AS summ_itemdet_co_line
     , @TtPickListSumm_TtItemdetCoRelease      AS summ_itemdet_co_release
     , @TtPickListSumm_TtItemdetUM             AS summ_itemdet_u_m
     , @TtPickListSumm_TtItemdetQtyRequired    AS summ_itemdet_qty_req
     , @TtPickList_Summary                     AS summary
     , @QtyUnitFormat                          AS qty_unit_format
     , @PlacesQtyUnit                          AS places_qty_unit
     , @QtyTotlFormat                          AS qty_totl_format
     , @PlacesQtyTot                           AS places_qty_Tot
   INTO #tt_orderpicklist_results
   WHERE 1=2

SET @Severity = 0
SET @PTExt    = NULL
SET @Infobar  = NULL

SET @PStartCoNum    = ISNULL(dbo.ExpandKyByType('CoNumType', @PStartCoNum), @LowCharacter)
SET @PEndCoNum      = ISNULL(dbo.ExpandKyByType('CoNumType', @PEndCoNum), @HighCharacter)
SET @PStartWhse     = ISNULL(@PStartWhse, @LowCharacter)
SET @PEndWhse       = ISNULL(@PEndWhse, @HighCharacter)
SET @PStartCustNum  = ISNULL(dbo.ExpandKyByType('CustNumType', @PStartCustNum), @LowCharacter)
SET @PEndCustNum    = ISNULL(dbo.ExpandKyByType('CustNumType', @PEndCustNum), @HighCharacter)
SET @PStartCustSeq  = ISNULL(@PStartCustSeq, dbo.LowInt())
SET @PEndCustSeq    = ISNULL(@pEndCustSeq, dbo.HighInt())

EXEC dbo.ApplyDateOffsetSp @PStartDueDate output, @DueDateStartingOffset, 0
EXEC dbo.ApplyDateOffsetSp @PEndDueDate output, @DueDateEndingOffset, 1
IF @PPostDate IS NOT NULL
   EXEC dbo.ApplyDateTimeOffsetSp @PPostDate output, @PostDateOffset


   ---- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   --IF OBJECT_ID(N'dbo.EXTGEN_Rpt_GenerateOrderPickListSp') IS NOT NULL
   --BEGIN
   --   DECLARE @EXTGEN_SpName sysname
   --   SET @EXTGEN_SpName = N'dbo.EXTGEN_Rpt_GenerateOrderPickListSp'
   --   -- Invoke the ETP routine, passing in (and out) this routine's parameters:
   --   EXEC @EXTGEN_SpName
   --      @PSessionIdChar
   --      , @PStartCoNum
   --      , @PEndCoNum
   --      , @PStartDueDate
   --      , @PEndDueDate
   --      , @PStartWhse
   --      , @PEndWhse
   --      , @PStartCustNum
   --      , @PEndCustNum
   --      , @PStartCustSeq
   --      , @PEndCustSeq
   --      , @PParmsSite
   --      , @PPostDate
   --      , @PPostMatlIssues
   --      , @PBarLoc
   --      , @PShowExternal
   --      , @PShowInternal
   --      , @PDisplayHeader
   --      , @PPrintBc
   --      , @PPrint80
   --      , @PDetSummBoth
   --      , @PPrItemCi
   --      , @PPrSerialNumbers
   --      , @PPrPlanItemMatl
   --      , @PPrStdOrderText
   --      , @PDisplayDescription
   --      , @PListByLoc
   --      , @PPickwarn
   --      , @PSuppressErrorWhenCustomerLcrNotReqd
   --      , @PSkipOrderLineCycCnt
   --      , @PProcessBatchId
   --      , @TaskId
   --      , @pPrintManufacturerItem
   --      , @DueDateStartingOffset
   --      , @DueDateEndingOffset
   --      , @PostDateOffset
   --      , @pSite

   --   EXEC dbo.CloseSessionContextSp @SessionID = @RptSessionID
   --   -- ETP routine must take over all desired functionality of this standard routine:
   --   RETURN
   --END
   ---- End of Generic External Touch Point code.

if @IfUsingExistingSession = 0
EXEC dbo.InitSessionContextWithUserSp
     @ContextName = 'Rpt_GenerateOrderPickListSp'
   , @Username    = @Username
   , @SessionID   = @RptSessionID
   , @Site        = @pSite 

DECLARE coCrs CURSOR LOCAL STATIC FOR
SELECT DISTINCT
  co.co_num
, coitem.whse
, co.cust_num
, co.cust_seq
FROM co WITH (READUNCOMMITTED) INNER JOIN coitem WITH (READUNCOMMITTED) ON coitem.co_num = co.co_num
WHERE  co.stat = 'O' AND (co.type = 'R' OR co.type = 'B')
  AND (co.co_num BETWEEN @PStartCoNum AND @PEndCoNum)
  AND (co.cust_num BETWEEN @PStartCustNum AND @PEndCustNum)
  AND (co.cust_seq BETWEEN @PStartCustSeq AND @PEndCustSeq)
  AND (coitem.whse BETWEEN @PStartWhse AND @PEndWhse)
  AND (coitem.due_date BETWEEN @PStartDueDate AND @PEndDueDate)
  AND coitem.ship_site = @PParmsSite
  AND coitem.stat = 'O'
ORDER BY co.cust_num, co.cust_seq, co.co_num, coitem.whse

OPEN coCrs
WHILE @Severity = 0
BEGIN
   FETCH coCrs INTO
        @CoCoNum
      , @CoitemWhse
      , @CoCustItem
      , @CoSeq

   IF @@FETCH_STATUS = -1
      BREAK

       
   EXEC @Severity = dbo.CheckWhseExternalControlledFlagSp
      @PWhse = @CoitemWhse
      ,@PSite = @PParmsSite
      ,@Infobar = @Infobar OUTPUT
   IF @Severity <> 0
   BEGIN
      SET @Severity = 0
      CONTINUE
   END
  
   IF @PPostMatlIssues = 1 AND OBJECT_ID('ExtSSSSHPRefCheckPickSp') IS NOT NULL
   BEGIN
      SET @SpName = 'dbo.ExtSSSSHPRefCheckPickSp'
      EXEC @Severity = @SpName @PSessionId, @CoCoNum

      IF @Severity <> 0
         GOTO AFTER_CO_LOOP
   END

   Exec @Severity = dbo.DefineVariableSp 
                           @VariableName  = 'SkipRecordDate', 
                           @VariableValue = 1, 
                           @Infobar = NULL
               
   EXEC @Severity = dbo.GenerateOrderPickListSp
                    @PSessionId                             = @PSessionId
                  , @PCoNum                                 = @CoCoNum
                  , @PStartDueDate                          = @PStartDueDate
                  , @PEndDueDate                            = @PEndDueDate
                  , @PWhse                                  = @CoitemWhse
                  , @PCustNum                               = @CoCustItem
                  , @PCustSeq                               = @CoSeq
                  , @PParmsSite                             = @PParmsSite
                  , @PPostDate                              = @PPostDate
                  , @PPostMatlIssues                        = @PPostMatlIssues
                  , @PBarLoc                                = @PBarLoc
                  , @PShowExternal                          = @PShowExternal
                  , @PShowInternal                          = @PShowInternal
                  , @PDisplayHeader                         = @PDisplayHeader
                  , @PPrintBc                               = @PPrintBc
                  , @PPrint80                               = @PPrint80
                  , @PDetSummBoth                           = @PDetSummBoth
                  , @PPrItemCi                              = @PPrItemCi
                  , @PPrSerialNumbers                       = @PPrSerialNumbers
                  , @PPrPlanItemMatl                        = @PPrPlanItemMatl
                  , @PPrStdOrderText                        = @PPrStdOrderText
                  , @PDisplayDescription                    = @PDisplayDescription
                  , @PListByLoc                             = @PListByLoc
                  , @PPickwarn                              = @PPickwarn
                  , @PSuppressErrorWhenCustomerLcrNotReqd   = @PSuppressErrorWhenCustomerLcrNotReqd
                  , @PSkipOrderLineCycCnt                   = @PSkipOrderLineCycCnt
                  , @PProcessBatchId                        = @TProcessBatchId
                  , @PText                                  = @PText
                  , @Infobar                                = @Infobar OUTPUT
                  
   Exec dbo.UndefineVariableSp 
         @VariableName  = 'SkipRecordDate',
         @Infobar = NULL

   IF @Severity <> 0
      GOTO END_OF_PROG
END
CLOSE      coCrs
DEALLOCATE coCrs

AFTER_CO_LOOP:

IF @Severity <> 0
   GOTO END_OF_PROG

IF @PPostMatlIssues = 1 AND OBJECT_ID(' ExtSSSSHPCleanupPickSp ') IS NOT NULL
BEGIN
   SET @SpName = 'dbo.ExtSSSSHPCleanupPickSp'
   EXEC @Severity = @SpName @PSessionId

   IF @Severity <> 0
      GOTO END_OF_PROG
END

IF OBJECT_ID('tempdb..#tt_order_pick_list_item_info') IS NULL
SELECT
    @TtOrderPickListItemInfo_TtItemtot_Whse          AS tt_itemtot_whse
  , @TtOrderPickListItemInfo_TtItemtot_Item          AS tt_itemtot_item
  , @TtOrderPickListItemInfo_TtItemtot_UM            AS tt_itemtot_um
  , @TtOrderPickListItemInfo_TtItemtot_QtyRequired   AS tt_itemtot_qty_req
  , @TtOrderPickListItemInfo_TtItemtot_QtyOnHand     AS tt_itemtot_qty_on_hand
  , @TtOrderPickListItemInfo_TtItemloclot_Loc        AS tt_itemloclot_loc
  , @TtOrderPickListItemInfo_TtItemloclot_Lot        AS tt_itemloclot_lot
  , @TtOrderPickListItemInfo_CoitemManufacturerId    AS manufacturer_id
  , @TtOrderPickListItemInfo_CoitemManufacturerItem  AS manufacturer_item
  , @TtOrderPickListItemInfo_TcQtuRequired           AS tc_qtu_required
  , @TtOrderPickListItemInfo_TtItemloclot_QtyOnHand  AS tt_itemloclot_qty_on_hand
  , @TtOrderPickListItemInfo_CustaddrName            AS custaddr_name
  , @TtOrderPickListItemInfo_TtItemdet_CoNum         AS tt_itemdet_co_num
  , @TtOrderPickListItemInfo_TtItemdet_CoLine        AS tt_itemdet_co_line
  , @TtOrderPickListItemInfo_TtItemdet_CoRelease     AS tt_itemdet_co_release
  , @TtOrderPickListItemInfo_TtItemdet_UM            AS tt_itemdet_u_m
  , @TtOrderPickListItemInfo_TtItemdet_QtyRequired   AS tt_itemdet_qty_req
INTO #tt_order_pick_list_item_info
WHERE 1=2

IF @PDetSummBoth <> 'D'
BEGIN
  EXEC dbo.GenerateOrderPickListCo14sRSp  @PSessionID = @PSessionID

  INSERT INTO #tt_orderpicklist_results(
       summ_itemtot_whse
     , summ_itemtot_item
     , summ_itemtot_um
     , summ_itemtot_qty_req
     , summ_itemtot_qty_on_hand
     , summ_itemloclot_loc
     , summ_itemloclot_lot
     , summ_itemmanufacturer_id
     , summ_itemmanufacturer_item
     , summ_tc_qtu_required
     , summ_itemloclot_qtyonhand
     , summ_custaddr_name
     , summ_itemdet_co_num
     , summ_itemdet_co_line
     , summ_itemdet_co_release
     , summ_itemdet_u_m
     , summ_itemdet_qty_req
     , summary               
     , qty_unit_format
     , places_qty_unit
     , qty_totl_format
     , places_qty_Tot
  )
  SELECT
       #tt_order_pick_list_item_info.tt_itemtot_whse
     , #tt_order_pick_list_item_info.tt_itemtot_item
     , #tt_order_pick_list_item_info.tt_itemtot_um
     , #tt_order_pick_list_item_info.tt_itemtot_qty_req
     , #tt_order_pick_list_item_info.tt_itemtot_qty_on_hand
     , #tt_order_pick_list_item_info.tt_itemloclot_loc
     , #tt_order_pick_list_item_info.tt_itemloclot_lot
     , #tt_order_pick_list_item_info.manufacturer_id
     , #tt_order_pick_list_item_info.manufacturer_item
     , #tt_order_pick_list_item_info.tc_qtu_required
     , #tt_order_pick_list_item_info.tt_itemloclot_qty_on_hand
     , #tt_order_pick_list_item_info.custaddr_name
     , #tt_order_pick_list_item_info.tt_itemdet_co_num
     , #tt_order_pick_list_item_info.tt_itemdet_co_line
     , #tt_order_pick_list_item_info.tt_itemdet_co_release
     , #tt_order_pick_list_item_info.tt_itemdet_u_m
     , #tt_order_pick_list_item_info.tt_itemdet_qty_req
     , 1   -- Summary Record
     , @QtyUnitFormat
     , @PlacesQtyUnit
     , @QtyTotlFormat
     , @PlacesQtyTot
  FROM #tt_order_pick_list_item_info
  LEFT JOIN itemloc WITH (READUNCOMMITTED)
  ON  itemloc.whse = #tt_order_pick_list_item_info.tt_itemtot_whse
  AND itemloc.item = #tt_order_pick_list_item_info.tt_itemtot_item
  AND itemloc.loc  = #tt_order_pick_list_item_info.tt_itemloclot_loc
  ORDER BY 
  #tt_order_pick_list_item_info.tt_itemtot_whse
, #tt_order_pick_list_item_info.tt_itemtot_item
, itemloc.rank
END -- SUMMARY

END_OF_PROG:
IF @Severity <> 0
BEGIN
   IF @TaskId IS NOT NULL
      EXEC dbo.AddProcessErrorLogSp @ProcessId = @TaskId, @InfobarText = @Infobar, @MessageSeverity = @Severity
   DELETE FROM #tt_orderpicklist_results
END

IF @PListByLoc = 1
  SELECT 
    co.RowPointer as co_RowPointer
  , isnull(co.UF_BackOrder, 'N') as 'BackOrder'
  , #tt_orderpicklist_results.co_contact
  , #tt_orderpicklist_results.co_cust_num
  , #tt_orderpicklist_results.co_cust_po
  , #tt_orderpicklist_results.co_cust_seq
  , #tt_orderpicklist_results.t_lcr
  , #tt_orderpicklist_results.coitem_RowPointer
  , #tt_orderpicklist_results.coparms_co_text_1
  , #tt_orderpicklist_results.coparms_co_text_2
  , #tt_orderpicklist_results.coparms_co_text_3
  , #tt_orderpicklist_results.co_co_num
  , #tt_orderpicklist_results.whse_whse
  , #tt_orderpicklist_results.coitem_co_line
  , #tt_orderpicklist_results.coitem_due_date
  , #tt_orderpicklist_results.coitem_qty_ordered
  , #tt_orderpicklist_results.tc_qtu_required1
  , #tt_orderpicklist_results.t_pickwarn2
  , #tt_orderpicklist_results.coitem_cust_item
  , #tt_orderpicklist_results.tc_qtu_s_qty1
  , #tt_orderpicklist_results.tc_qtu_short1
  , #tt_orderpicklist_results.s_loc
  , #tt_orderpicklist_results.s_lot
  , #tt_orderpicklist_results.tc_qtud_on_hand1
  , #tt_orderpicklist_results.t_exception
  , #tt_orderpicklist_results.tc_qtu_rsvd_qty1
  , #tt_orderpicklist_results.coitem_co_release
  , #tt_orderpicklist_results.coitem_item
  , #tt_orderpicklist_results.item_u_m
  , #tt_orderpicklist_results.description
  , #tt_orderpicklist_results.manufacturer_id
  , #tt_orderpicklist_results.manufacturer_item
  , #tt_orderpicklist_results.billto_addr1
  , #tt_orderpicklist_results.billto_addr2
  , #tt_orderpicklist_results.billto_addr3
  , #tt_orderpicklist_results.billto_addr4
  , #tt_orderpicklist_results.billto_city
  , #tt_orderpicklist_results.billto_country
  , #tt_orderpicklist_results.billto_name
  , #tt_orderpicklist_results.billto_state
  , #tt_orderpicklist_results.billto_zip
  , #tt_orderpicklist_results.billto_contact
  , #tt_orderpicklist_results.billto_phone
  , dbo.MultiLineAddressSp(billto_name, billto_addr1, billto_addr2, billto_addr3, billto_addr4, billto_city, 
  billto_state, billto_zip, billto_country, billto_contact) AS billto_longaddr
  , #tt_orderpicklist_results.cred_hold
  , #tt_orderpicklist_results.shipcode_desc
  , #tt_orderpicklist_results.shipto_addr1
  , #tt_orderpicklist_results.shipto_addr2
  , #tt_orderpicklist_results.shipto_addr3
  , #tt_orderpicklist_results.shipto_addr4
  , #tt_orderpicklist_results.shipto_city
  , #tt_orderpicklist_results.shipto_country
  , #tt_orderpicklist_results.shipto_name
  , #tt_orderpicklist_results.shipto_state
  , #tt_orderpicklist_results.shipto_zip
  , #tt_orderpicklist_results.shipto_contact
  , #tt_orderpicklist_results.shipto_phone
  , dbo.MultiLineAddressSp(shipto_name, shipto_addr1, shipto_addr2, shipto_addr3, shipto_addr4, shipto_city, 
  shipto_state, shipto_zip, shipto_country, shipto_contact) AS shipto_longaddr
  , #tt_orderpicklist_results.terms_desc
  , #tt_orderpicklist_results.tmp_ser_ser_num  
  , #tt_orderpicklist_results.co_d_config_feat_str
  , #tt_orderpicklist_results.co_d_config_qty_conv
  , #tt_orderpicklist_results.co_d_config_u_m
  , #tt_orderpicklist_results.co_d_config_desc    
  , #tt_orderpicklist_results.NoteExists
  , #tt_orderpicklist_results.summ_itemtot_whse
  , #tt_orderpicklist_results.summ_itemtot_item
  , #tt_orderpicklist_results.summ_itemtot_um
  , #tt_orderpicklist_results.summ_itemtot_qty_req
  , #tt_orderpicklist_results.summ_itemtot_qty_on_hand
  , #tt_orderpicklist_results.summ_itemloclot_loc
  , #tt_orderpicklist_results.summ_itemloclot_lot
  , #tt_orderpicklist_results.summ_itemmanufacturer_id
  , #tt_orderpicklist_results.summ_itemmanufacturer_item
  , #tt_orderpicklist_results.summ_tc_qtu_required
  , #tt_orderpicklist_results.summ_itemloclot_qtyonhand
  , #tt_orderpicklist_results.summ_custaddr_name
  , #tt_orderpicklist_results.summ_itemdet_co_num
  , #tt_orderpicklist_results.summ_itemdet_co_line
  , #tt_orderpicklist_results.summ_itemdet_co_release
  , #tt_orderpicklist_results.summ_itemdet_u_m
  , #tt_orderpicklist_results.summ_itemdet_qty_req
  , #tt_orderpicklist_results.summary
  , #tt_orderpicklist_results.qty_unit_format
  , #tt_orderpicklist_results.places_qty_unit
  , #tt_orderpicklist_results.qty_totl_format
  , #tt_orderpicklist_results.places_qty_Tot
  FROM #tt_orderpicklist_results join co (nolock) on co.co_num = #tt_orderpicklist_results.co_co_num 
  ORDER BY
       #tt_orderpicklist_results.summary
     , #tt_orderpicklist_results.whse_whse
     , #tt_orderpicklist_results.co_co_num
     , #tt_orderpicklist_results.s_loc
     , #tt_orderpicklist_results.s_lot
     , #tt_orderpicklist_results.coitem_item
     , #tt_orderpicklist_results.coitem_co_line
     , #tt_orderpicklist_results.coitem_co_release
     , #tt_orderpicklist_results.summ_itemtot_whse
     , #tt_orderpicklist_results.summ_itemtot_item
     , #tt_orderpicklist_results.summ_custaddr_name
     , #tt_orderpicklist_results.summ_itemloclot_loc
     , #tt_orderpicklist_results.summ_itemloclot_lot
     , #tt_orderpicklist_results.summ_itemdet_co_num
     , #tt_orderpicklist_results.summ_itemdet_co_release
ELSE    -- @PListByLoc = 0
  SELECT 
   co.RowPointer as co_RowPointer
  , isnull(co.UF_BackOrder, 'N') as 'BackOrder'
  , #tt_orderpicklist_results.co_contact
  , #tt_orderpicklist_results.co_cust_num
  , #tt_orderpicklist_results.co_cust_po
  , #tt_orderpicklist_results.co_cust_seq
  , #tt_orderpicklist_results.t_lcr
  , #tt_orderpicklist_results.coitem_RowPointer
  , #tt_orderpicklist_results.coparms_co_text_1
  , #tt_orderpicklist_results.coparms_co_text_2
  , #tt_orderpicklist_results.coparms_co_text_3
  , #tt_orderpicklist_results.co_co_num
  , #tt_orderpicklist_results.whse_whse
  , #tt_orderpicklist_results.coitem_co_line
  , #tt_orderpicklist_results.coitem_due_date
  , #tt_orderpicklist_results.coitem_qty_ordered
  , #tt_orderpicklist_results.tc_qtu_required1
  , #tt_orderpicklist_results.t_pickwarn2
  , #tt_orderpicklist_results.coitem_cust_item
  , #tt_orderpicklist_results.tc_qtu_s_qty1
  , #tt_orderpicklist_results.tc_qtu_short1
  , #tt_orderpicklist_results.s_loc
  , #tt_orderpicklist_results.s_lot
  , #tt_orderpicklist_results.tc_qtud_on_hand1
  , #tt_orderpicklist_results.t_exception
  , #tt_orderpicklist_results.tc_qtu_rsvd_qty1
  , #tt_orderpicklist_results.coitem_co_release
  , #tt_orderpicklist_results.coitem_item
  , #tt_orderpicklist_results.item_u_m
  , #tt_orderpicklist_results.description
  , #tt_orderpicklist_results.manufacturer_id
  , #tt_orderpicklist_results.manufacturer_item
  , #tt_orderpicklist_results.billto_addr1
  , #tt_orderpicklist_results.billto_addr2
  , #tt_orderpicklist_results.billto_addr3
  , #tt_orderpicklist_results.billto_addr4
  , #tt_orderpicklist_results.billto_city
  , #tt_orderpicklist_results.billto_country
  , #tt_orderpicklist_results.billto_name
  , #tt_orderpicklist_results.billto_state
  , #tt_orderpicklist_results.billto_zip
  , #tt_orderpicklist_results.billto_contact
  , #tt_orderpicklist_results.billto_phone
  , dbo.MultiLineAddressSp(billto_name, billto_addr1, billto_addr2, billto_addr3, billto_addr4, billto_city, 
  billto_state, billto_zip, billto_country, billto_contact) AS billto_longaddr  
  , #tt_orderpicklist_results.cred_hold
  , #tt_orderpicklist_results.shipcode_desc
  , #tt_orderpicklist_results.shipto_addr1
  , #tt_orderpicklist_results.shipto_addr2
  , #tt_orderpicklist_results.shipto_addr3
  , #tt_orderpicklist_results.shipto_addr4
  , #tt_orderpicklist_results.shipto_city
  , #tt_orderpicklist_results.shipto_country
  , #tt_orderpicklist_results.shipto_name
  , #tt_orderpicklist_results.shipto_state
  , #tt_orderpicklist_results.shipto_zip
  , #tt_orderpicklist_results.shipto_contact
  , #tt_orderpicklist_results.shipto_phone
  , dbo.MultiLineAddressSp(shipto_name, shipto_addr1, shipto_addr2, shipto_addr3, shipto_addr4, shipto_city, 
  shipto_state, shipto_zip, shipto_country, shipto_contact) AS shipto_longaddr  
  , #tt_orderpicklist_results.terms_desc
  , #tt_orderpicklist_results.tmp_ser_ser_num  
  , #tt_orderpicklist_results.co_d_config_feat_str
  , #tt_orderpicklist_results.co_d_config_qty_conv
  , #tt_orderpicklist_results.co_d_config_u_m
  , #tt_orderpicklist_results.co_d_config_desc    
  , #tt_orderpicklist_results.NoteExists
  , #tt_orderpicklist_results.summ_itemtot_whse
  , #tt_orderpicklist_results.summ_itemtot_item
  , #tt_orderpicklist_results.summ_itemtot_um
  , #tt_orderpicklist_results.summ_itemtot_qty_req
  , #tt_orderpicklist_results.summ_itemtot_qty_on_hand
  , #tt_orderpicklist_results.summ_itemloclot_loc
  , #tt_orderpicklist_results.summ_itemloclot_lot
  , #tt_orderpicklist_results.summ_itemmanufacturer_id
  , #tt_orderpicklist_results.summ_itemmanufacturer_item
  , #tt_orderpicklist_results.summ_tc_qtu_required
  , #tt_orderpicklist_results.summ_itemloclot_qtyonhand
  , #tt_orderpicklist_results.summ_custaddr_name
  , #tt_orderpicklist_results.summ_itemdet_co_num
  , #tt_orderpicklist_results.summ_itemdet_co_line
  , #tt_orderpicklist_results.summ_itemdet_co_release
  , #tt_orderpicklist_results.summ_itemdet_u_m
  , #tt_orderpicklist_results.summ_itemdet_qty_req
  , #tt_orderpicklist_results.summary 
  , #tt_orderpicklist_results.qty_unit_format
  , #tt_orderpicklist_results.places_qty_unit
  , #tt_orderpicklist_results.qty_totl_format
  , #tt_orderpicklist_results.places_qty_Tot
  FROM #tt_orderpicklist_results
join co (nolock) on co.co_num = #tt_orderpicklist_results.co_co_num 
  
  LEFT JOIN itemloc itemlocDetail WITH (READUNCOMMITTED)
  ON  itemlocDetail.whse = #tt_orderpicklist_results.whse_whse
  AND itemlocDetail.item = #tt_orderpicklist_results.coitem_item
  AND itemlocDetail.loc  = #tt_orderpicklist_results.s_loc
  LEFT JOIN itemloc itemlocSummary WITH (READUNCOMMITTED)
  ON  itemlocSummary.whse = #tt_orderpicklist_results.summ_itemtot_whse
  AND itemlocSummary.item = #tt_orderpicklist_results.summ_itemtot_item
  AND itemlocSummary.loc  = #tt_orderpicklist_results.summ_itemloclot_loc
  ORDER BY
       #tt_orderpicklist_results.summary
     , #tt_orderpicklist_results.whse_whse
     , #tt_orderpicklist_results.co_co_num
     , #tt_orderpicklist_results.coitem_co_line
     , #tt_orderpicklist_results.coitem_co_release
     , itemlocDetail.rank
     , #tt_orderpicklist_results.s_lot
     , #tt_orderpicklist_results.tmp_ser_ser_num
     , #tt_orderpicklist_results.summ_itemtot_whse
     , #tt_orderpicklist_results.summ_itemtot_item
     , #tt_orderpicklist_results.summ_custaddr_name
     , itemlocSummary.rank
     , #tt_orderpicklist_results.summ_itemloclot_lot
     , #tt_orderpicklist_results.summ_itemdet_co_num
     , #tt_orderpicklist_results.summ_itemdet_co_release

   IF OBJECT_ID('tempdb..#tt_order_pick_list_item_info') IS NOT NULL
     DROP TABLE #tt_order_pick_list_item_info

   IF OBJECT_ID('tempdb..#tt_orderpicklist_results') IS NOT NULL
     DROP TABLE #tt_orderpicklist_results

   DELETE
   FROM tmp_pick_itemloclot
   WHERE SessionID = @PSessionId

   DELETE
   FROM tmp_pick_itemdet
   WHERE SessionID = @PSessionId

   DELETE
   FROM tmp_pick_itemtot
   WHERE SessionID = @PSessionId

if @IfUsingExistingSession = 0
   EXEC dbo.CloseSessionContextSp @SessionID = @RptSessionID

RETURN 0

GO


