USE [KPI_App]
GO

/****** Object:  StoredProcedure [dbo].[ShipLotDefaultSp]    Script Date: 09/06/2017 11:24:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* $Header: /ApplicationDB/Stored Procedures/ShipLotDefaultSp.sp 14    9/04/11 6:27a Ddeng $  */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2008 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
***************************************************************
*/

/* $Archive: /ApplicationDB/Stored Procedures/ShipLotDefaultSp.sp $
 *
 * SL8.03 14 142267 Ddeng Sun Sep 04 06:27:38 2011
 * The lot will be changed to the default lot when quantity is changed.
 * Issue 142267
 * Use lot in the where clause. If no record return, get the default lot.
 *
 * SL8.03 13 138366 Cajones Fri Aug 12 10:57:50 2011
 * Quantity Move not setting Lot Number correctly
 * Issue 138366 
 * Removed code that caused stored procedure to exit without doing lot lookup if the passed in @Lot number is populated(Code was orignally added for issue 83134)
 *
 * SL8.02 12 rs4588 Dahn Thu Mar 04 16:40:10 2010
 * rs4588 copyright header changes
 *
 * SL8.01 11 rs3953 Vlitmano Tue Aug 26 19:08:10 2008
 * RS3953 - Changed a Copyright header?
 *
 * SL8.01 10 rs3953 Vlitmano Mon Aug 18 15:40:52 2008
 * Changed a Copyright header information(RS3959)
 *
 * SL8.00 9 RS2968 nkaleel Fri Feb 23 05:18:29 2007
 * changing copyright information(RS2968)
 *
 * SL8.00 8 RS2968 prahaladarao.hs Wed Jul 12 02:45:43 2006
 * RS 2968, Name change CopyRight Update.
 *
 * SL7.05 7 91818 NThurn Fri Jan 06 18:16:45 2006
 * Inserted standard External Touch Point call.  (RS3177)
 *
 * SL7.04 6 91500 Hcl-tayamoh Fri Jan 21 13:46:55 2005
 * Add WITH (READUNCOMMITTED) to item_all AND lot_loc_all
 * 91500
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE [dbo].[ShipLotDefaultSp](
  @Site        SiteType = NULL
, @Whse        WhseType
, @Item        ItemType
, @Loc         LocType
, @Lot         LotType          OUTPUT
, @Infobar     InfobarType      OUTPUT
, @ImportDocId ImportDocIdType  OUTPUT
) AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ShipLotDefaultSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ShipLotDefaultSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
         @Site
         , @Whse
         , @Item
         , @Loc
         , @Lot OUTPUT
         , @Infobar OUTPUT
         , @ImportDocId OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
 
-- ROUTINE:
--   item/slotdef.i - Shipping LOT Default
-- PURPOSE:
--    This program finds the proper default for shipping lot.
DECLARE
  @Severity       INT
, @TaxFreeMatl    ListYesNoType

SET @Severity    = 0
SET @TaxFreeMatl = 0

IF @Site IS NULL
BEGIN
   SELECT
     @Site = site
   FROM parms
   WHERE parm_key = 0
END

SELECT @TaxFreeMatl = tax_free_matl
FROM item_all WITH (READUNCOMMITTED)
WHERE item = @Item AND site_ref = @Site

IF @TaxFreeMatl = 1
BEGIN
  SELECT TOP 1
  @Lot = tfiqa.lot
 ,@ImportDocId = tfiqa.import_doc_id
  FROM tax_free_import_qty_all AS tfiqa
  WHERE tfiqa.site_ref = @Site
    AND tfiqa.whse     = @Whse
    AND tfiqa.loc      = @Loc
    AND tfiqa.item     = @Item
  ORDER BY tfiqa.site_ref, tfiqa.whse, tfiqa.item,
         tfiqa.lot, tfiqa.loc
END

SELECT TOP 1
  @Lot = lot_loc_all.lot
FROM lot_loc_all WITH (READUNCOMMITTED)
WHERE lot_loc_all.site_ref = @Site
AND lot_loc_all.whse = @Whse
AND lot_loc_all.loc  = @Loc
AND lot_loc_all.item = @Item
AND (lot_loc_all.Lot  = @Lot OR @Lot IS NULL)
ORDER BY lot_loc_all.site_ref, lot_loc_all.whse, lot_loc_all.item,
         lot_loc_all.lot, lot_loc_all.loc

IF @@ROWCOUNT = 0
BEGIN
    SELECT TOP 1
      @Lot = lot_loc_all.lot
    FROM lot_loc_all WITH (READUNCOMMITTED)
    WHERE lot_loc_all.site_ref = @Site
    AND lot_loc_all.whse = @Whse
    AND lot_loc_all.loc  = @Loc
    AND lot_loc_all.item = @Item
    ORDER BY lot_loc_all.site_ref, lot_loc_all.whse, lot_loc_all.item,
            lot_loc_all.lot, lot_loc_all.loc
END


RETURN @Severity
GO


